/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/query/sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Sql */
        post: operations["query_sql_query_sql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/rag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Rag Endpoint */
        post: operations["query_rag_endpoint_query_rag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Endpoint */
        post: operations["analyze_endpoint_query_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refund/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refund Evaluate Endpoint */
        post: operations["refund_evaluate_endpoint_refund_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observability/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests Endpoint */
        get: operations["list_requests_endpoint_observability_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observability/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request Endpoint */
        get: operations["get_request_endpoint_observability_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tickets Draft Endpoint */
        post: operations["tickets_draft_endpoint_tickets_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tickets Confirm Endpoint */
        post: operations["tickets_confirm_endpoint_tickets_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invoices Draft Endpoint */
        post: operations["invoices_draft_endpoint_invoices_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invoices Confirm Endpoint */
        post: operations["invoices_confirm_endpoint_invoices_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Question */
            question: string;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Answer */
            answer: string;
            /** Sql Used */
            sql_used: boolean;
            /** Rag Used */
            rag_used: boolean;
            /** Grounded */
            grounded: boolean;
            /** Ungrounded Claims */
            ungrounded_claims: string[];
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /**
             * Incomplete
             * @default false
             */
            incomplete: boolean;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Topic Coverage Warning
             * @default false
             */
            topic_coverage_warning: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvoiceConfirmRequest */
        InvoiceConfirmRequest: {
            /** Draft Id */
            draft_id: string;
        };
        /** InvoiceConfirmResponse */
        InvoiceConfirmResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "error";
            /** Invoice Id */
            invoice_id?: string | null;
            /** Validation Status */
            validation_status?: ("validated" | "flagged" | "duplicate") | null;
            /** Flagged Reasons */
            flagged_reasons?: string[] | null;
            /** Error Reason */
            error_reason?: string | null;
        };
        /** InvoiceDraftRequest */
        InvoiceDraftRequest: {
            /** Image Base64 */
            image_base64: string;
            /**
             * Media Type
             * @enum {string}
             */
            media_type: "image/jpeg" | "image/png";
        };
        /** InvoiceDraftResponse */
        InvoiceDraftResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "drafted" | "could_not_process";
            /** Draft Id */
            draft_id?: string | null;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Invoice Number */
            invoice_number?: string | null;
            /** Invoice Date */
            invoice_date?: string | null;
            /** Subtotal Cents */
            subtotal_cents?: number | null;
            /** Tax Cents */
            tax_cents?: number | null;
            /** Total Cents */
            total_cents?: number | null;
            /** Line Items */
            line_items?: {
                [key: string]: unknown;
            }[] | null;
            /** Field Confidence */
            field_confidence?: {
                [key: string]: number;
            } | null;
            /** Validation Status */
            validation_status?: ("validated" | "flagged" | "duplicate") | null;
            /** Flagged Reasons */
            flagged_reasons?: string[] | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Expires In Seconds */
            expires_in_seconds?: number | null;
        };
        /** RagChunkResult */
        RagChunkResult: {
            /** Content */
            content: string;
            /** Source Doc */
            source_doc: string;
            /** Rule Number */
            rule_number: number | null;
            /** Similarity */
            similarity: number;
        };
        /** RagQueryRequest */
        RagQueryRequest: {
            /** Question */
            question: string;
            /**
             * K
             * @default 3
             */
            k: number;
        };
        /** RagQueryResponse */
        RagQueryResponse: {
            /** Chunks */
            chunks: components["schemas"]["RagChunkResult"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** RefundEvaluateRequest */
        RefundEvaluateRequest: {
            /** Request Text */
            request_text: string;
        };
        /** RefundEvaluateResponse */
        RefundEvaluateResponse: {
            /** Status */
            status: string;
            /** Rule Applied */
            rule_applied: number | null;
            /** Reasoning */
            reasoning: string;
            /** Extracted Fields */
            extracted_fields: {
                [key: string]: unknown;
            };
        };
        /**
         * RequestLogDetailRow
         * @description Full single-row detail, returned by GET /observability/requests/{id}.
         *     tool_calls is NULL for every request type except 'analyze' — see the
         *     column comment on RequestLog.tool_calls.
         */
        RequestLogDetailRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Request Type */
            request_type: string;
            /** Input */
            input: string;
            /** Output */
            output: unknown;
            /** Latency Ms */
            latency_ms: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: number | null;
            /** Grounded */
            grounded: boolean | null;
            /** Sql Query Audit Id */
            sql_query_audit_id: string | null;
            /** Rag Chunks Retrieved */
            rag_chunks_retrieved: unknown | null;
            /** Cached */
            cached: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallEntry"][] | null;
        };
        /** RequestLogListResponse */
        RequestLogListResponse: {
            /** Requests */
            requests: components["schemas"]["RequestLogRow"][];
        };
        /**
         * RequestLogRow
         * @description Summary shape used by the list endpoint. Deliberately excludes
         *     tool_calls — a full per-call trace is only meaningful for one request at
         *     a time, and including it on every row of a list response would bloat a
         *     50-row page with payloads nobody's looking at yet. See
         *     RequestLogDetailRow for the single-row detail endpoint.
         */
        RequestLogRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Request Type */
            request_type: string;
            /** Input */
            input: string;
            /** Output */
            output: unknown;
            /** Latency Ms */
            latency_ms: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Estimated Cost Usd */
            estimated_cost_usd: number | null;
            /** Grounded */
            grounded: boolean | null;
            /** Sql Query Audit Id */
            sql_query_audit_id: string | null;
            /** Rag Chunks Retrieved */
            rag_chunks_retrieved: unknown | null;
            /** Cached */
            cached: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SourceRef */
        SourceRef: {
            /** Rule Number */
            rule_number: number | null;
            /** Source Doc */
            source_doc: string;
        };
        /** SqlQueryRequest */
        SqlQueryRequest: {
            /** Question */
            question: string;
        };
        /** SqlQueryResponse */
        SqlQueryResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "rejected" | "error";
            /** Sql Executed */
            sql_executed?: string | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /**
             * Rows
             * @default []
             */
            rows: {
                [key: string]: unknown;
            }[];
            /**
             * Row Count
             * @default 0
             */
            row_count: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Execution Time Ms */
            execution_time_ms?: number | null;
            /** Estimated Cost */
            estimated_cost?: number | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** TicketConfirmRequest */
        TicketConfirmRequest: {
            /** Draft Id */
            draft_id: string;
        };
        /** TicketConfirmResponse */
        TicketConfirmResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "error";
            /** Ticket Id */
            ticket_id?: string | null;
            /** Error Reason */
            error_reason?: string | null;
        };
        /** TicketDraftRequest */
        TicketDraftRequest: {
            /** Request Text */
            request_text: string;
        };
        /** TicketDraftResponse */
        TicketDraftResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "drafted" | "could_not_process";
            /** Draft Id */
            draft_id?: string | null;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /** Customer Id */
            customer_id?: string | null;
            /** Order Id */
            order_id?: string | null;
            /** Product Id */
            product_id?: string | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Expires In Seconds */
            expires_in_seconds?: number | null;
            /** Unresolved Fields */
            unresolved_fields?: string[] | null;
        };
        /**
         * ToolCallEntry
         * @description One tool invocation within /query/analyze's tool-call loop. sequence
         *     is the call's position across the *entire* loop (all iterations), not
         *     reset per iteration, so the ordered trace survives even when the loop
         *     calls multiple tools in one turn or spans several turns.
         */
        ToolCallEntry: {
            /** Tool Name */
            tool_name: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: unknown;
            /** Latency Ms */
            latency_ms: number;
            /** Sequence */
            sequence: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_sql_query_sql_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SqlQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_rag_endpoint_query_rag_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_endpoint_query_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refund_evaluate_endpoint_refund_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundEvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundEvaluateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_endpoint_observability_requests_get: {
        parameters: {
            query?: {
                request_type?: ("sql" | "rag" | "analyze" | "refund_evaluate" | "ticket_draft" | "ticket_confirm") | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_endpoint_observability_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestLogDetailRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tickets_draft_endpoint_tickets_draft_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tickets_confirm_endpoint_tickets_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoices_draft_endpoint_invoices_draft_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoices_confirm_endpoint_invoices_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
