"""add cached column to request_log

Revision ID: 33d3b07087f4
Revises: 5e0936314556
Create Date: 2026-07-16 19:35:59.476884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d3b07087f4'
down_revision: Union[str, Sequence[str], None] = '5e0936314556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_log', sa.Column('cached', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_log', 'cached')
    # ### end Alembic commands ###
