"""add shipments table

Revision ID: 3f4300144152
Revises: 33d3b07087f4
Create Date: 2026-07-17 16:36:50.795029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f4300144152'
down_revision: Union[str, Sequence[str], None] = '33d3b07087f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.Text(), nullable=False),
    sa.Column('shipped_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actual_delivery_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('pending','shipped','delivered','delayed')", name='shipments_status_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipments_order_id', 'shipments', ['order_id'], unique=False)
    op.create_index('ix_shipments_status', 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipments_status', table_name='shipments')
    op.drop_index('ix_shipments_order_id', table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
