"""add request_log table

Revision ID: 5e0936314556
Revises: 030baca5fcfd
Create Date: 2026-07-10 21:03:04.934043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e0936314556'
down_revision: Union[str, Sequence[str], None] = '030baca5fcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Text(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=True),
    sa.Column('sql_query_audit_id', sa.UUID(), nullable=True),
    sa.Column('rag_chunks_retrieved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("request_type IN ('sql','rag','analyze','refund_evaluate')", name='request_log_request_type_check'),
    sa.ForeignKeyConstraint(['sql_query_audit_id'], ['query_audit_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_log_created_at', 'request_log', ['created_at'], unique=False)
    op.create_index('ix_request_log_request_type', 'request_log', ['request_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_log_request_type', table_name='request_log')
    op.drop_index('ix_request_log_created_at', table_name='request_log')
    op.drop_table('request_log')
    # ### end Alembic commands ###
