"""add web_analytics and campaigns tables

Revision ID: 8fb0658c0657
Revises: 95c1697ff650
Create Date: 2026-07-24 17:19:54.719469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb0658c0657'
down_revision: Union[str, Sequence[str], None] = '95c1697ff650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("channel IN ('email','paid_search','paid_social','influencer','organic')", name='campaigns_channel_check'),
    sa.CheckConstraint("status IN ('planned','active','ended')", name='campaigns_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_analytics')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
